# Generated by Django 3.1.7 on 2021-03-16 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210316_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
