# Generated by Django 3.1.7 on 2021-03-16 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
