# Generated by Django 3.1.7 on 2021-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210316_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
    ]
