# Generated by Django 3.1.7 on 2021-03-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_status_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='start_bid',
        ),
    ]
