# Generated by Django 3.1.7 on 2021-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(default='Others', max_length=64),
            preserve_default=False,
        ),
    ]
