# Generated by Django 3.1.7 on 2021-03-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.categories'),
        ),
    ]
